language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgtk-3-dev

script:
  - cargo build --verbose --all
  - cargo build --verbose --examples
  - cargo test --verbose --all

before_deploy:
  - cargo doc --no-deps

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  local_dir: ./target/doc
